CREATE TABLE ALUMNOS(
ID_ALUMNOS NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(30),
APELLIDOS VARCHAR2(60),
F_NACIMIENTO DATE
);

INSERT INTO ALUMNOS (ID_ALUMNOS, NOMBRE, APELLIDOS, F_NACIMIENTO) VALUES 
    (1, 'PABLO', 'HERNANDEZ MATA', 1995-03-14);
INSERT INTO ALUMNOS (ID_ALUMNOS, NOMBRE, APELLIDOS, F_NACIMIENTO) VALUES    
    (2, 'JEREMIAS', 'SANTOS LOTE', 1993-07-12);
INSERT INTO ALUMNOS (ID_ALUMNOS, NOMBRE, APELLIDOS, F_NACIMIENTO) VALUES
    (3, 'TERESA', 'LOMAS TRILLO', 1989-06-19);
INSERT INTO ALUMNOS (ID_ALUMNOS, NOMBRE, APELLIDOS, F_NACIMIENTO) VALUES
    (4, 'MARTA', 'FUEGO GARCIA', 1992-11-23);
INSERT INTO ALUMNOS (ID_ALUMNOS, NOMBRE, APELLIDOS, F_NACIMIENTO) VALUES
    (5, 'SERGIO', 'OT DIRMET', 1991-04-21);
INSERT INTO ALUMNOS (ID_ALUMNOS, NOMBRE, APELLIDOS, F_NACIMIENTO) VALUES
    (6, 'CARMEN', 'DILMA PERNA', 1987-12-04);

CREATE TABLE PROFES(
ID_PROFE NUMBER PRIMARY KEY,
NOMBRE_P VARCHAR2 (30),
APELLIDOS_P VARCHAR (60),
F_NACIMIENTO_P DATE
);

INSERT INTO PROFES (ID_PROFE, NOMBRE_P, APELLIDOS_P, F_NACIMIENTO_P) VALUES 
    (1, 'FEDERICO', 'GASCO DAZA', 1975-04-23);
INSERT INTO PROFES (ID_PROFE, NOMBRE_P, APELLIDOS_P, F_NACIMIENTO_P) VALUES 
    (2, 'ANA', 'SAURA TRENZO', 1969-08-02);
INSERT INTO PROFES (ID_PROFE, NOMBRE_P, APELLIDOS_P, F_NACIMIENTO_P) VALUES 
    (3, 'ROSA', 'HONROSA PEREZ', 1980-09-05);
INSERT INTO PROFES (ID_PROFE, NOMBRE_P, APELLIDOS_P, F_NACIMIENTO_P) VALUES 
    (4, 'CARLOS', 'GARCIA MARTINEZ', 1985-05-24);

CREATE TABLE CURSOS(
ID_CURSOS NUMBER PRIMARY KEY,
TITULO VARCHAR2(30),
ID_PROFE NUMBER

CONSTRAINT FK_ID_PROFE
FOREIGN KEY (RELACION)
REFERENCES PROFES (ID_PROFE)
);

INSERT INTO CURSOS (ID_CURSO, TITULO, ID_PROFE) VALUES 
    (1, 'PROGRAMACION PHP');
INSERT INTO CURSOS (ID_CURSO, TITULO, ID_PROFE) VALUES 
    (2, 'MODELOS ABSTRACTO DE DATOS');
INSERT INTO CURSOS (ID_CURSO, TITULO, ID_PROFE) VALUES 
    (3, 'SQL DESDE CERO');
INSERT INTO CURSOS (ID_CURSO, TITULO, ID_PROFE) VALUES 
    (4, 'DIBUJO TECNICO');
INSERT INTO CURSOS (ID_CURSO, TITULO, ID_PROFE) VALUES 
    (5, 'SQL AVANZADO');

CREATE TABLE ALUMNOS_CURSOS(
ID_ALUMNOS NUMBER,
ID_CURSOS NUMBER

CONSTRAINT FK_ID_ALUMNOS, FK_ID_CURSOS
FOREIGN KEY (RELACION1)
REFERENCES ALUMNOS (ID_ALUMNOS), CURSOS (ID_CURSOS)
);

