CREATE TABLE ARTIST(
ID_ARTI NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_ARTISTA VARCHAR2(30) NOT NULL,
NUM_SEGUIDORES NUMBER,
UlTIMO_SEN VARCHAR2(30)
);

CREATE TABLE GENERO(
ID_GENERO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TIPO_GENERO VARCHAR2(40)
);

CREATE TABLE USUARIO(
   ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   NOMBRE_USUARIO VARCHAR2(30),
   EMAIL VARCHAR2(30),
   CONTRA VARCHAR2(15),
   SEGUIDORES NUMBER
);

CREATE TABLE SUSCRIPCION(
ID_SUSCRIPCION  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TIPO_SUB VARCHAR2(20),
ID_USUARIO NUMBER,
CONSTRAINT FK_SUSCRIPCION FOREIGN KEY(ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE SONGS(
ID_SONGS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_CANCION VARCHAR2 (30),
DURACION NUMBER(4,2),
ID_GENERO NUMBER,
ID_ARTI NUMBER,
CONSTRAINT FK_SONGS FOREIGN KEY(ID_ARTI)REFERENCES ARTIST(ID_ARTI),
FOREIGN KEY(ID_GENERO)REFERENCES GENERO(ID_GENERO)
);

CREATE TABLE ALBUMS(
ID_ALBUMS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_ALBUM VARCHAR2(60),
FECHA_LANZAMIENTO DATE,
DURACION NUMBER(4,2),
ID_ARTISTA NUMBER,
ID_SONG NUMBER,
CONSTRAINT FK_ALBUMS FOREIGN KEY (ID_ARTISTA) REFERENCES ARTIST(ID_ARTI),
FOREIGN KEY (ID_SONG) REFERENCES SONGS(ID_SONGS)
);


CREATE TABLE PLAYLIST(
ID_PLAYLIST NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_PLAYLIST VARCHAR2(40),
PRIVACIDAD_PLAYLIST VARCHAR2(30),
DURACION_PLAYLIST NUMBER(4,2),
ID_SONGS NUMBER,
CONSTRAINT FK_PLAYLIST FOREIGN KEY(ID_SONGS)REFERENCES SONGS(ID_SONGS)
);

CREATE TABLE PLAYLIST_USUARIO(
ID_PLAYLIST_USUARIOS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_PLAYLIST VARCHAR2(40),
PRIVACIDAD_PLAYLIST VARCHAR2(30),
DURACION_PLAYLIST NUMBER(4,2),
ID_SONGS NUMBER,
ID_USUA NUMBER,
CONSTRAINT FK_PLAYLIST_USUARIOS FOREIGN KEY(ID_SONGS)REFERENCES SONGS(ID_SONGS),
FOREIGN KEY(ID_USUA)REFERENCES USUARIO(ID_USUARIO)
);