/* TABLAS*/

CREATE TABLE ARTIST(
ID_ARTI NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_ARTISTA VARCHAR2(50) NOT NULL,
NUM_SEGUIDORES NUMBER(20,0),
ULTIMO_SEN VARCHAR2(50)
);


CREATE TABLE GENEROS(
ID_GENERO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TIPO_GENERO VARCHAR2(40)
);


CREATE TABLE USUARIO(
   ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   NOMBRE_USUARIO VARCHAR2(40),
   EMAIL VARCHAR2(40),
   CONTRA VARCHAR2(20),
   SEGUIDORES NUMBER
);



CREATE TABLE SUSCRIPCION(
ID_SUSCRIPCION  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TIPO_SUB VARCHAR2(50),
ID_USUARIO NUMBER,
CONSTRAINT FK_SUSCRIPCION FOREIGN KEY(ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
);


CREATE TABLE SONGS(
ID_SONGS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_CANCION VARCHAR2 (50),
DURACION NUMBER,
ID_GENERO NUMBER,
ID_ARTI NUMBER,
CONSTRAINT FK_SONGS FOREIGN KEY(ID_ARTI)REFERENCES ARTIST(ID_ARTI),
FOREIGN KEY(ID_GENERO)REFERENCES GENEROS(ID_GENERO)
);


CREATE TABLE ALBUMS(
ID_ALBUMS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_ALBUM VARCHAR2(60),
FECHA_LANZAMIENTO DATE,
DURACION NUMBER(4,2),
ID_ARTISTA NUMBER,

CONSTRAINT FK_ALBUMS FOREIGN KEY (ID_ARTISTA) REFERENCES ARTIST(ID_ARTI)
);

CREATE TABLE PLAYLIST(
ID_PLAYLIST NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_PLAYSLIST VARCHAR2(40),
PRIVACIDAD_PLAYLIST VARCHAR2(30),
DURACION_PLAYSLIST NUMBER(4,2),
ID_ARTI NUMBER,
CONSTRAINT FK_PLAYSLIST FOREIGN KEY(ID_ARTI)REFERENCES ARTIST(ID_ARTI)
);


CREATE TABLE PLAYSLIST_USUARIOS(
ID_PLAYLIST_USUARIOS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_PLAYSLIST VARCHAR2(40),
PRIVACIDAD_PLAYLIST VARCHAR2(30),
DURACION_PLAYSLIST NUMBER(4,2),
ID_SONGS NUMBER,
ID_USUA NUMBER,
CONSTRAINT FK_PLAYSLIST_USUARIOS FOREIGN KEY(ID_SONGS)REFERENCES SONGS(ID_SONGS),
FOREIGN KEY(ID_USUA)REFERENCES USUARIO(ID_USUARIO)
);









/* DATOS*/

INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('stevie ray vaughan y double trobule ',347865,'pride and joy');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('b.b king',1072864,'we are the world');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('robert johnson ',4208687,'Sweet Home Chicago');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('alan waker ',29384217,'Spectre 2.0');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('martin garrix',1100926,'Reboot');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('avicci',9234651,'Ten More Days');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('cartel de santa',1198835,'Ya No Van ');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('xxxtentacion',1929482,'UGLY');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Dr. Dre',937260,'Genocide');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Rascal Flatts',623846,'My Wish');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Zach Bryan',4984501,'Something in the Orange');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Morgan Wallen',812091,'Last Night');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Tom Odell',901285,'Another Love');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Paris Paloma',1945829,'Labour');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Cordelia',826593,'Little Life');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('gorilaz ',7198336,'souk eye');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('MGMT',998264,'Little Dark Age');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('WALTER ASTRAL',1985642,'Le feu');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Theo Croker',10934967,'somethin');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('norah jones ',1094568,'have yourself a merry little chrismas');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Louis Armstrong',1028458,'what a wonderful world');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('natanael cano',94573487,'o me voy o te vas');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('peso pluma ',198563,'la bebe');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('bad bunny',12463871,'un x100to');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('BTS',23857672,'My universe');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('twice',48756125,'the feels');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('black pink',198464,'shut down');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Lana del Rey',1984562,'Sweet,AW');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('LRain',12498536,'Sweet,AW');
INSERT INTO ARTIST(NOMBRE_ARTISTA, NUM_SEGUIDORES,ULTIMO_SEN) VALUES('Slowdive',148653287,'Our Funeral');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Rels B',229822,'Sin Gato');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Taylor Swift',1592440,'Karma, Lover');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Dua Lipa ',337456,'New Rules');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Mettalica',3820421,'Screaming Suicide');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Iron Maiden',7324282,'The Writing on the Wall');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Pantera',7898166,'Walk');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('bob marley ',2100533,'African Herbsman');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('cultura profetica ',4147197,'Despertador Solar');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('lee "scratch" perry',3983835,'Jealousy');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('banda ms ',220800,'No es invento mio');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('calibre 50',18887,'Quien te crees');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('grupo firme ',25896458,'Mi vida en 2');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('belanova',4659841,'rosa pastel');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('mon laferte',36547495,'mi buen amor');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('jesse y joy',878965,'No soy una de esas');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Maneskin',3645125,'Beggin');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Blink-182',58746878,'Mutt');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('The Killers',325697,'Caution');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Ozuna',85479654,'Dile que tu me quieres');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Daddy Yankee',548856,'Gasolina');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Wisin y Yandel',2547896,'Un ladron');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Quevedo',698534,'Vista al mar');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Feid',24965469,'Nieve');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('Rauw Alejandro',58746,'No me la moleste ');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('jose jose ',54789654,'el triste');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('luis miguel',365896,'Pupilas de gato');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('alfredo olivas',36526,'Seguramente');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('eminem',58964785,'Square Dance');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('nf',8547965,'10 Feet Down');
INSERT INTO ARTIST(NOMBRE_ARTISTA,NUM_SEGUIDORES,ULTIMO_SEN)VALUES('ice cube',5789657,'The predator');



INSERT INTO GENEROS (TIPO_GENERO) VALUES('Blues');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Electrónica');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Hip-hop');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Country');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Folk');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Alternativa');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Jazz');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Latina');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Kpop');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Indie');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Pop');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Metal');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Reggae');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Banda');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Pop latino');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Rock');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Reggaeton');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Urbano');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Regional mexicano');
INSERT INTO GENEROS (TIPO_GENERO) VALUES('Rap');



INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Olivia Johnson',' user1@example.com','pass123',1);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Ethan Miller','user2@example.com','abc456',2);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Sophia Davis','testuser@email.com','qwerty789',3);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Jackson Turner',' demo@gmail.com','demoPass',4);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Ava Mitchell',' fakeuser@hotmail.com','mySecret123',5);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Liam Carter',' exampleuser@yahoo.com','testpass456',6);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Isabella Walker',' testing123@outlook.com','passTest789',7);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Noah Bennett','userdemo@mail.com','demo1234',8);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Emma Parker','tempuser@domain.com','securePwd789',9);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Lucas Taylor',' mytestuser@gmail.com','pass123abc',10);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Alejandro Gómez','alejandro.gomez@gmail.com','P@ssword123',11);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Carolina Herrera','carolina.herrera@gmail.com','SecurePass456',12);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Martín Sánchez','martin.sanchez@gmail.com','MySecret789',13);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Valentina Torres','valentina.torres@gmail.com','HiddenPass432',14);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Sebastián Méndez','sebastian.mendez@gmail.com',' StrongP@ss!',15);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Isabella Ramírez','isabella.ramirez@gmail.com','SecretCode876',16);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Javier Mendoza','javier.mendoza@gmail.com','ProtectedPass111',17);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Sofía Castro',' sofia.castro@gmail.com','SafeWord222',18);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Diego López','diego.lopez@gmail.com','SuperSecr3t!',19);
INSERT INTO USUARIO(NOMBRE_USUARIO,EMAIL,CONTRA,SEGUIDORES) VALUES('Camila Ruiz','camila.ruiz@gmail.com','Private1234!',20);



INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium individual',1);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Free',2);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium familiar',3);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium Duo',4);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium individual',5);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Free',6);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium familiar',7);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium familiar',8);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Free',9);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium familiar',10);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium familiar',11);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium individual',12);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium individual',13);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium Duo',14);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Free',15);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium familiar',16);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium Duo',17);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Free',18);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Premium Duo',19);
INSERT INTO SUSCRIPCION(TIPO_SUB,ID_USUARIO) VALUES('Free',20);




INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('pride and joy', 4.20,1,1);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('little wing', 5.50,1,1);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('look at little sister', 4.15,1,1);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Love Struck Baby', 4.20,1,1);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Rude Mood Hide Away', 5.50,1,1);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Shake for Me', 4.15,1,1);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('we are the world', 4.00,1,2);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('the thrill is gone', 4.05,1,2);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('lonesome chirismas', 5.55,1,2);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('so excited', 4.00,1,2);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('no good', 4.05,1,2);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('you re losin me ', 5.55,1,2);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('me and the devil blues', 4.30,1,3);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('stones in my passway', 6.10,1,3);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('sweet home chicago', 5.20,1,3);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES (' Kind Hearted Woman Blues', 4.30,1,3);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('I Believe I ll Dust My Broom', 6.10,1,3);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('sweet home chicago', 5.20,1,3);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('faded', 4.05,2,4);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('spectre', 3.50,2,4);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Heart over Mind', 5.05,2,4);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('alon', 4.05,2,4);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Welcome to Walkerworld', 3.50,2,4);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES (' Heart over Mind', 5.05,2,4);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('in the name of love', 4.30,2,5);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('scared to be lonely', 7.00,2,5);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Reboot', 4.15,2,5);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('animals', 4.30,2,5);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Follow', 7.00,2,5);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Limitless', 4.15,2,5);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Ten More Days', 4.25,2,6);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Touch Me', 4.10,2,6);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('waiting for love', 5.20,2,6);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Talk To Myself', 4.25,2,6);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('hey brother', 4.10,2,6);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('wake me up', 5.20,2,6);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Ya No Van', 6.00,3,7);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('burbujas de cristal', 4.35,3,7);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Súbete y Ya Verás', 3.40,3,7);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Pa No Andar Triste', 6.00,3,7);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('bombos y tarolas', 4.35,3,7);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('party', 3.40,3,7);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('UGLY', 4.30,3,8);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('sad!', 3.45,3,8);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('look at me', 5.00,3,8);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('moonlight', 4.30,3,8);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('introduction', 3.45,3,8);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Ex Bitch', 5.00,3,8);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Genocide', 4.10,3,9);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('the next episode', 420,3,9);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Talk About It', 550,3,9);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('still D.R.E', 4.10,3,9);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Intro', 420,3,9);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('uthin but a g thang', 550,3,9);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('In A Hurry', 415,4,10);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('My Wish', 400,4,10);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('How They Remember You', 405,4,10);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Fast', 415,4,10);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Life is a Highwa', 400,4,10);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Feel It In The Morning', 405,4,10);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Something in the Orange', 555,4,11);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Heading South', 430,4,11);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Summertimes Close', 610,4,11);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Dawns', 555,4,11);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Fear and Fridays', 430,4,11);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Overtime', 610,4,11);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Somebodys Problem', 520,4,12);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Last Night', 405,4,12);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Wasted On You', 350,4,12);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('You Proof', 520,4,12);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Sand In My Boots', 405,4,12);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Cover Me Up', 350,4,12);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Another Love', 505,5,13);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Black Friday', 430,5,13);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Best Day Of My Life', 700,5,13);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Sad Anymore', 505,5,13);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Sunrise', 430,5,13);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Heal', 700,5,13);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('cradle', 415,5,14);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('echo', 425,5,14);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Labour', 410,5,14);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Yeti', 415,5,14);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('mulled wine', 425,5,14);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('The fruits', 410,5,14);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Just a Crush', 520,5,15);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Little Life', 600,5,15);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI)VALUES ('Play Pretend', 435,5,15);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Caramel', 520,5,15);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Lay Me Down', 600,5,15);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI)VALUES ('What I Wouldnt Do', 435,5,15);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('dare', 640,6,16);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('with guns', 430,6,16);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('souk eye', 345,6,16);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('feel good', 640,6,16);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('plastic beach', 430,6,16);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES (' cracker island', 345,6,16);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Me and Michael', 500,6,17);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Little Dark Age', 410,6,17);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('When You Die', 4.20,6,17);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Me and Michael', 500,6,17);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Little Dark Age', 410,6,17);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('When You Die', 4.20,6,17);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Serpent Mental', 5.50,6,18);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Le feu', 4.15,6,18);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Hyperdruide', 4.00,6,18);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Serpent Mental', 5.50,6,18);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Le feu', 4.15,6,18);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Hyperdruide', 4.00,6,18);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('TO BE WE', 4.05,7,19);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('JAZZ IS DEAD', 5.55,7,19);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('good day', 4.30,7,19);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('LOVE QUANTUM', 4.05,7,19);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('theo says', 5.55,7,19);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('somethin', 4.30,7,19);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Little Broken Hearts', 6.10,7,20);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Say Goodbye', 5.20,7,20);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Good Morning', 4.05,7,20);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('have yourself a merry little chrismas', 6.10,7,20);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('chrismas dont be', 5.20,7,20);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('late', 4.05,7,20);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('You Turned The Tables On Me', 3.50,7,21);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('what a won derful world', 5.05,7,21);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('it dont men a thing', 4.30,7,21);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('when the saint go marching in', 3.50,7,21);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Youre The Top', 5.05,7,21);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('When Your Lover Has Gone', 4.30,7,21);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('La Lokerona', 7.00,8,22);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('o me voy o te vas', 4.15,8,22);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Diran De Mi', 4.25,8,22);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('lou lou', 7.00,8,22);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Mas Altas Que Bajadas', 4.15,8,22);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('prc', 4.25,8,22);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('lady gaga', 4.10,8,23);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('la bebe', 5.20,8,23);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('qlona', 6.00,8,23);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('77', 4.10,8,23);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('ROSA PASTEL', 5.20,8,23);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('LUNA', 6.00,8,23);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Me Porto Bonito', 4.35,8,24);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Después de la Playa', 6.40,8,24);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Moscow Mule', 4.30,8,24);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('ojitos negros', 4.35,8,24);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('monaco', 6.40,8,24);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('un x100to', 4.30,8,24);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('My universe', 3.15,9,25);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Dynamite', 5.00,9,25);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Fake Love', 2.20,9,25);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Life Goes On ', 3.20,9,25);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Fly to My Room', 4.20,9,25);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Blue and Gray', 3.10,9,25);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('The feels', 6.00,9,26);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('What is love', 4.00,9,26);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('I cant stop me', 3.00,9,26);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('MOONLIGHT SUNRISE', 5.30,9,26);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('The feels', 3.20,9,26);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('SET ME FREE', 2.20,9,26);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Shut me down', 5.00,9,27);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Pink venom', 3.40,9,27);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('How you like that', 4.10,9,27);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Ice cream', 3.20,9,27);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Pretty savage', 3.30,9,27);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('venom', 2.50,9,27);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Say yes to heaven', 4.10,10,28);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Summertime Sadness', 2.21,10,28);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Radio', 3.22,10,28);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('The grants',2.21,10,28);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Sweet', 3.24,10,28);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('AW', 4.32,10,28);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Pet rock', 5.23,10,29);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Our Funeral', 2.24,10,29);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('I killed your dog ', 2.45,10,29);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Sincerely Commercial', 4.21,10,29);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Our funeral',3.20,10,29);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Commercial',3.27,10,29);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Alisson',5.37,10,30);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('40 Days',2.57,10,30);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Kisses',3.25,10,30);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Shanty',1.36,10,30);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Prayer remembered',4.25,10,30);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Alife',4.23,10,30);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Sonrie <3', 4.10,11,31);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('miamor', 4.10,11,31);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Por dentro', 4.05,11,31);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('AfroLOVA', 4.10,11,31);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Un Rodeoooo', 4.10,11,31);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Sin Gato', 4.10,11,31);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Style', 4.10,11,32);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Bad Blood', 4.10,11,32);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Shake It Off', 4.10,11,32);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Blank Space', 4.10,11,32);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Karma', 4.10,11,32);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Lover', 4.10,11,32);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Houdini', 4.10,11,33);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Don t Start Now', 4.10,11,33);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('New Rules', 4.10,11,33);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Future Nostalgia', 4.10,11,33);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Don t Start Now', 4.10,11,33);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Cool', 4.10,11,33);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Enter Sandman', 4.10,12,34);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Nothing Else Matters', 4.10,12,34);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('One', 4.10,12,34);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('72 Seasons', 4.10,12,34);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Shadows Follow', 4.10,12,34);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Screaming Suicide', 4.10,12,34);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('The Trooper', 4.10,12,35);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Run to the Hills', 4.10,12,35);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Fear of the Dark', 4.10,12,35);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Senjutsu', 4.10,12,35);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Stratego', 4.10,12,35);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('The Writing on the Wall', 4.10,12,35);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Walk', 4.10,12,36);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Cowboys from Hell', 4.10,12,36);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Cementery Gates', 4.10,12,36);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('War Nerve', 4.10,12,36);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Drag the Waters', 4.10,12,36);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('10 s', 4.10,12,36);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('could you be love', 4.10,13,37);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('is this love', 4.10,13,37);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('three little birds', 4.10,13,37);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Don t Rock My Boat', 4.10,13,37);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Soul Rebel', 4.10,13,37);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES (' African Herbsman', 4.10,13,37);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('ilegal', 4.10,13,38);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('saca prende y sorprende', 4.10,13,38);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('la complicidad', 4.10,13,38);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Sobrevolando', 4.10,13,38);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Efecto Dominó', 4.10,13,38);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Despertador Solar', 4.10,13,38);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Saint Selassie', 4.10,13,39);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Sinful Fuckers', 4.10,13,39);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Rolling Thunder', 4.10,13,39);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('The Game Black', 4.10,13,39);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Yee Ha ha ha', 4.10,13,39);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Jealousy', 4.10,13,39);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('el color de tus ojos', 4.10,14,40);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('ojos cerrados', 4.10,14,40);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('me vas a extrañar', 4.10,14,40);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Me gusta tu vieja', 4.10,14,40);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Hablame de ti', 4.10,14,40);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('No es invento mio', 4.10,14,40);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('si te pudiera mentir', 4.10,14,41);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('a la antiguita', 4.10,14,41);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES (' hoy mas que nunca', 4.10,14,41);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Kani', 4.10,14,41);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('La caja de pan', 4.10,14,41);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Quien te crees', 4.10,14,41);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('el amor de su vida', 4.10,14,42);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('el toxico', 4.10,14,42);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('que onda perdida', 4.10,14,42);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Algo tranqui', 4.10,14,42);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Efectos de alcohol', 4.10,14,42);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Mi vida en 2', 4.10,14,42);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('rosa pastel', 4.10,15,43);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('cada que', 4.10,15,43);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('no me voy a morir', 4.10,15,43);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Por esta vez', 4.10,15,43);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('One Two Three GO', 4.10,15,43);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Rockstar', 4.10,15,43);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('mi buen amor', 4.10,15,44);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('tu falta querer', 4.10,15,44);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('amarrame', 4.10,15,44);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('que si', 4.10,15,44);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Ana', 4.10,15,44);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Primaveral', 4.10,15,44);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('dueles', 4.10,15,45);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('corre', 4.10,15,45);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('te esperare', 4.10,15,45);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Que pena me da', 4.10,15,45);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Ecos de amor', 4.10,15,45);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('No soy una de esas', 4.10,15,45);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('BEGGIN',4.12,16,46);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('HONEY',3.12,16,46);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('I WANNA BE YOUR SLAVE',4.12,16,46);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('CHOSEN',2.12,16,46);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('VENGO DALLA LUNA',3.12,16,46);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('RECOVERY',2.12,16,46);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('I MISS YOU',3.12,16,47);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('ONE MORE TIME',2.10,16,47);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('FIRST DATE',3.40,16,47);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('ALIENS EXIST',2.40,16,47);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('ADAMS SONGS',2.12,16,47);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('MUTT',4.12,16,47);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('SOMEBODY TOLD ME',3.12,16,48);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('HUMAN',3.02,16,48);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('ALL THESE THINGS THAT IVE DONE',3.02,16,48);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('BE STILL',2.45,16,48);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('THE MAN',4.12,16,48);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('CAUTION',3.02,16,48);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('SE PREPARO',4.12,17,49);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('EL FARSANTE',3.12,17,49);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('DILE QUE TU ME QUIERES',4.12,17,49);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('TU FOTO',2.12,17,49);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('SE PREPARO',3.50,17,49);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('DILE QUE TU ME QUIERES',2.12,17,49);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('GASOLINA',4.12,17,50);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('LO QUE PASO PASO',3.12,17,50);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('LA SANTA',2.12,17,50);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('TEMBLOR',3.20,17,50);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('POSE',2.05,17,50);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('LLAMADO DE EMERGENCIA',2.50,17,50);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('VAPOR',2.12,17,51);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('CALIENTE',5.85,17,51);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('DELITOS',2.12,17,51);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('LA REALIDAD',3.10,17,51);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('UN LADRON',4.50,17,51);
INSERT INTO SONGS(NOMBRE_CANCION,DURACION,ID_GENERO,ID_ARTI)VALUES('Todos Quieren bailar contigo',4.50,17,51);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Columbia', 4.10,18,52);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Punto G', 4.10,18,52);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('No pienso llamar', 4.10,18,52);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Ahora que', 4.10,18,52);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Yankee', 4.10,18,52);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Vista al mar', 4.10,18,52);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Perro Negro', 4.10,18,53);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Feliz Cumpleaños Fercho', 4.10,18,53);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Hey Mor', 4.10,18,53);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('X20X', 4.10,18,53);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Lady mi amor', 4.10,18,53);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Nieve', 4.10,18,53);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Diluvio', 4.10,18,54);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Beso', 4.10,18,54);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Te felicito', 4.10,18,54);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Cuando Baje el Sol', 4.10,18,54);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Cuki', 4.10,18,54);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('No me la moleste', 4.10,18,54);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('el triste', 4.10,19,55);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('vamos a darnos tiempo', 4.10,19,55);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('el amar y el quere', 4.10,19,55);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Lo dudo', 4.10,19,55);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('El amor Acaba', 4.10,19,55);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Voy a llenarte toda', 4.10,19,55);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('la incondicional', 4.10,19,56);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('hasta que me olvides', 4.10,19,56);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Fria como el viento', 4.10,19,56);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Esa niña', 4.10,19,56);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Culpable o no', 4.10,19,56);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Pupilas de gato', 4.10,19,56);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('El paciente', 4.10,19,57);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('El precio de la Soledad', 4.10,19,57);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('El sillon', 4.10,19,57);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('El problema', 4.10,19,57);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Todo o nada', 4.10,19,57);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Seguramente', 4.10,19,57);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Rap god',2.25,20,58);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Slim shady',5.15,20,58);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Monster',3.31,20,58);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('White america',2.45,20,58);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Business',4.45,20,58);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Square Dance',2.45,20,58);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('The search',2.15,20,59);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('If you want love',2.25,20,59);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Happy',3.15,20,59);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Outcast',4.25,20,59);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('10 Feet down',2.25,20,59);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('xdxdxd',2.25,20,59);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('It was a good day',2.15,20,60);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('you know we do it',5.20,20,60);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Chaek yo self',1.15,20,60);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Im scared ',3.54,20,60);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('Im scared wicked',2.15,20,60);
INSERT INTO SONGS (NOMBRE_CANCION, DURACION,ID_GENERO,ID_ARTI) VALUES ('The predator',2.15,20,60);



INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Completely Well','25-11-1975',1.45,2);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Walkerworld','12-04-1987',2.87,4);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Compton','03-09-1971',3.12,9);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Dangerous','18-06-1985',4.65,12);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('cemeteries and socials','05-02-2000',5.93,14);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Hyperdruide','22-08-1992',6.21,18);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Pops Is Tops','30-01-1965',7.76,21);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('GÉNESIS','14-11-1978',8.45,23);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('BE','07-07-1983',9.98,25);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('everything is alive','19-03-1969',1.56,30);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('1989','02-05-1995',2.32,32);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Senjutsu','11-12-1977',3.78,35);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Bob Marley','03-04-1989',4.09,37);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Simplemente Gracias','28-06-1963',5.67,41);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Fantasia pop','16-09-1970',6.54,43);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Chosen','08-01-2005',7.88,46);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Odisea','22-05-1967',8.23,49);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Playa Saturno','10-07-1981',9.77,54);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Secretos','04-03-1998',1.43,55);
INSERT INTO ALBUMS(NOMBRE_ALBUM,FECHA_LANZAMIENTO,DURACION,ID_ARTISTA)
VALUES('Perception','17-10-2008',2.65,59);



INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('ELECTRONIC HOUSE','PUBLICA',4.15,5);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('ELECTRONIC HOUSE','PUBLICA',4.15,5);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('SAD','PUBLICA',3.15,8);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('RAP URBANO','PUBLICA',2.50,7);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('PA DOLIDOS','PUBLICA',3.54,57);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('RAP INGLES','PUBLICA',4.50,58);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('PA PISTEAR','PUBLICA',5.20,42);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('THS RELS B','PUBLICA',2.50,31);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('EXITOS DEL MOMENTO','PRIVADA',4.15,32);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('ICE CREAM','PUBLICA',3.78,27);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('GORILAZ-EXITOS','PUBLICA',3.15,16);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('TOP MOMENTS AVICCI','PRIVADA',7.45,6);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('ELECTRO 2010','PUBLICA',3.60,4);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('EN ACAPULCO CON JOSE JOSE','PUBLICA',5.20,55);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('EL GOAT','PUBLICA',7.45,50);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('WISIN Y YANDEL TEMAS VIEJITOS','PUBLICA',4.15,51);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('ANTRO','PUBLICA',5.20,52);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('CON QUIEN SE QUEDA EL PERRO','PRIVADA',2.15,45);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('ROCK-EXITOS','PUBLICA',2.78,46);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('LIMON Y SAL','PRIVADA',8.12,44);
INSERT INTO PLAYLIST(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_ARTI)VALUES('NATA MONTANA','PUBLICA',4.15,22);



INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('100% Corridazos','publica',31,1,1);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Pon reggaeton','publica',31,2,2);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Pop','Privada',31,3,3);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Raperos Mexas','Publica',31,4,4);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Rap','Privada',31,5,5);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('LuisMI','Privada',31,6,6);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('De todo un poco','Privada',31,7,7);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('En Ingles','Privada',31,8,8);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Aleatorio','Privada',31,8,8);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Reino urbano','Privada',31,9,9);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Lo Mejor en Vivo','Privada',31,10,10);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Carnita Asada','publica',99,11,11);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Viva Latino','publica',50,12,12);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Exitos en Mexico','publica',68,13,13);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('La lista Pop','publica',88,13,13);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Banda','Privada',91,13,13);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Corridos tumbados','Privada',41,14,14);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Reggaeton','Privada',51,15,15);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Karaoke','publica',61,16,16);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Top artistas Mexico','publica',71,17,17);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Top Artistas Mexico','Privada',81,18,18);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Pistiembre','publica',91,19,19);
INSERT INTO PLAYSLIST_USUARIOS(NOMBRE_PLAYSLIST,PRIVACIDAD_PLAYLIST,DURACION_PLAYSLIST,ID_SONGS,ID_USUA) VALUES ('Favoritas','Privada',31,20,20);





/* CONSULTAS */

-- ARTISTA --

SELECT * FROM ARTIST WHERE NUM_SEGUIDORES > 50000 AND ULTIMO_SEN = 'Reboot';

SELECT * 
FROM ARTIST 
WHERE UPPER(NOMBRE_ARTISTA) LIKE '%Y%';

SELECT *  FROM ARTIST 
WHERE UPPER(NOMBRE_ARTISTA) LIKE '%XXX%';

SELECT * FROM ARTIST ORDER BY NUM_SEGUIDORES DESC;

SELECT * FROM ARTIST WHERE NUM_SEGUIDORES > 1000000;

SELECT * FROM ARTIST WHERE ULTIMO_SEN = 'Sweet Home Chicago';

SELECT COUNT(*) FROM ARTIST;


SELECT * FROM ARTIST WHERE NUM_SEGUIDORES < 1000000 ORDER BY NOMBRE_ARTISTA;


SELECT SUM(NUM_SEGUIDORES) AS TOTAL_SEGUIDORES FROM ARTIST;

SELECT * FROM ARTIST WHERE UPPER(SUBSTR(ULTIMO_SEN, 1, 1)) = 'S';



-- GENERO --

SELECT * FROM GENEROS;

SELECT * FROM GENEROS WHERE ID_GENERO = 3;

SELECT COUNT(*) AS TOTAL_GENEROS FROM GENEROS;

SELECT * FROM GENEROS WHERE UPPER(TIPO_GENERO) LIKE '%POP%';

SELECT * FROM GENEROS ORDER BY TIPO_GENERO ASC;

SELECT * FROM GENEROS WHERE ROWNUM <= 5;

SELECT * FROM GENEROS WHERE UPPER(TIPO_GENERO) NOT IN ('ROCK', 'POP');

SELECT * FROM GENEROS ORDER BY TIPO_GENERO ASC;

SELECT * FROM GENEROS WHERE ROWNUM <= 5;

SELECT * FROM GENEROS WHERE UPPER(TIPO_GENERO) NOT IN ('Indie', 'Regional mexicano', 'Reggaeton' );


-- USUARIO --

SELECT * FROM USUARIO ORDER BY NOMBRE_USUARIO;

SELECT NOMBRE_USUARIO, SEGUIDORES
FROM USUARIO
WHERE SEGUIDORES > 10;

SELECT U.ID_USUARIO, U.NOMBRE_USUARIO, U.EMAIL, S.TIPO_SUB
FROM USUARIO U
INNER JOIN SUSCRIPCION S ON U.ID_USUARIO = S.ID_USUARIO;

SELECT NOMBRE_USUARIO, EMAIL
FROM USUARIO
WHERE ID_USUARIO IN (SELECT ID_USUARIO FROM SUSCRIPCION WHERE TIPO_SUB = 'Premium individual');

SELECT NOMBRE_USUARIO, EMAIL
FROM USUARIO
WHERE ID_USUARIO IN (SELECT ID_USUARIO FROM SUSCRIPCION WHERE TIPO_SUB = 'Free');

SELECT NOMBRE_USUARIO, EMAIL
FROM USUARIO
WHERE ID_USUARIO IN (SELECT ID_USUARIO FROM SUSCRIPCION WHERE TIPO_SUB = 'Premium familiar');

SELECT U.ID_USUARIO, U.NOMBRE_USUARIO, U.EMAIL, S.TIPO_SUB
FROM USUARIO U
INNER JOIN SUSCRIPCION S ON U.ID_USUARIO = S.ID_USUARIO;

SELECT NOMBRE_USUARIO, EMAIL
FROM USUARIO
WHERE ID_USUARIO IN (SELECT ID_USUARIO FROM SUSCRIPCION WHERE TIPO_SUB = 'Premium individual');

SELECT NOMBRE_USUARIO, EMAIL
FROM USUARIO
WHERE ID_USUARIO IN (SELECT ID_USUARIO FROM SUSCRIPCION WHERE TIPO_SUB = 'Free');

SELECT NOMBRE_USUARIO, EMAIL
FROM USUARIO
WHERE ID_USUARIO IN (SELECT ID_USUARIO FROM SUSCRIPCION WHERE TIPO_SUB = 'Premium familiar');


SELECT NOMBRE_USUARIO AS NOMBRE
FROM USUARIO
ORDER BY NOMBRE_USUARIO DESC;

SELECT NOMBRE_USUARIO, CONTRA AS PASSWORD
FROM USUARIO;


-- SUSCRIPCION --


--1.Seleccionar todas las suscripciones
SELECT * FROM SUSCRIPCION;

--2.Seleccionar las suscripciones de tipo "Premium individual"
SELECT * FROM SUSCRIPCION WHERE TIPO_SUB = 'Premium individual';

--3.Seleccionar las suscripciones de tipo "Free" para un usuario específico (por ejemplo, usuario con ID 2)
SELECT * FROM SUSCRIPCION WHERE TIPO_SUB = 'Free' AND ID_USUARIO = 2;

--4.Contar el número total de suscripciones
SELECT COUNT(*) AS TOTAL_SUSCRIPCIONES FROM SUSCRIPCION;

--5.Seleccionar suscripciones ordenadas por tipo de suscripción de forma ascendente
SELECT * FROM SUSCRIPCION ORDER BY TIPO_SUB ASC;

--6.Encontrar el ID de suscripción máximo
SELECT MAX(ID_SUSCRIPCION) AS MAX_ID_SUSCRIPCION FROM SUSCRIPCION;

--7.Seleccionar suscripciones de usuarios con ID entre 5 y 10 Rango de Usuarios
SELECT * FROM SUSCRIPCION WHERE ID_USUARIO BETWEEN 5 AND 10;

--8.Contar el número de suscripciones de tipo "Premium familiar"
SELECT COUNT(*) AS TOTAL_PREMIUM_FAMILIAR FROM SUSCRIPCION WHERE TIPO_SUB = 'Premium familiar';

--9.Mostrar la información de suscripción junto con el nombre del usuario
SELECT S.*, U.NOMBRE_USUARIO
FROM SUSCRIPCION S
JOIN USUARIO U ON S.ID_USUARIO = U.ID_USUARIO;

--10.Seleccionar la cantidad de suscripciones por tipo
SELECT TIPO_SUB, COUNT(*) AS CANTIDAD_SUSCRIPCIONES
FROM SUSCRIPCION
GROUP BY TIPO_SUB;

SELECT S.TIPO_SUB, COUNT(U.ID_USUARIO) AS NUMERO_DE_USUARIOS
FROM SUSCRIPCION S
LEFT JOIN USUARIO U ON S.ID_USUARIO = S.ID_SUSCRIPCION
GROUP BY S.TIPO_SUB;

-- SONGS -- 

--Primera Consulta de todos los usuarios que tienen una playlist personalizada--
SELECT U.NOMBRE_USUARIO,PU.NOMBRE_PLAYSLIST FROM USUARIO U INNER JOIN PLAYSLIST_USUARIOS PU ON U.ID_USUARIO=PU.ID_USUA;

--Segunda consulta de todos los artistas y el numero de seguidores--
SELECT AR.NOMBRE_ARTISTA, AR.NUM_SEGUIDORES FROM ARTIST AR;

--Tercera Consulta donde Se muestran las canciones con su respectivo genero--
SELECT G.TIPO_GENERO AS GENERO, S.NOMBRE_CANCION FROM GENEROS G INNER JOIN SONGS S ON G.ID_GENERO = S.ID_GENERO;

--Cuarta Consulta donde se muestra el nombre del artista, sus canciones y la duracion de cada una-- 
SELECT A.NOMBRE_ARTISTA, S.NOMBRE_CANCION, S.DURACION FROM ARTIST A INNER JOIN SONGS S ON A.ID_ARTI =  S.ID_ARTI;

-- Quinta Consulta donde se muestra el nombre de usuario y el tipo de suscripcion que tiene cada uno --
SELECT S.NOMBRE_USUARIO AS NOMBRE, SUS.TIPO_SUB AS SUSCRIPCION FROM USUARIO S INNER JOIN SUSCRIPCION SUS ON S.ID_USUARIO = SUS.ID_USUARIO;

-- Sexta Consulta donde se muestran cada una de las suscripciones y el numero de personas que tienen cada uno --
SELECT TIPO_SUB AS SUSCRIPCION, COUNT(*) AS NOPERSONAS FROM SUSCRIPCION GROUP BY TIPO_SUB;

-- Septima consulta donde se muestran la playlist de los usuarios y el numero de canciones que tienen            una--
SELECT DISTINCT PS.NOMBRE_PLAYSLIST, (SELECT COUNT(*) FROM SONGS S WHERE PS.ID_SONGS = S.ID_SONGS) AS NOCANCIONES
FROM PLAYSLIST_USUARIOS;

--Octava consulta donde se muestran todos los nombres de artistsas y su numero de canciones --
SELECT A.NOMBRE_ARTISTA, COUNT(*) AS NOCANCIONES FROM ARTIST A INNER JOIN SONGS S ON A.ID_ARTI = S.ID_ARTI GROUP BY A.NOMBRE_ARTISTA;

--Novena consulta donde se muestra cada uno de los generos y el numero de canciones que tiene cada uno -- 
SELECT G.TIPO_GENERO AS GENERO, COUNT (*) AS NOCANCIONES FROM GENEROS G INNER JOIN SONGS S ON G.ID_GENERO = S.ID_GENERO
GROUP BY G.TIPO_GENERO;

--Decima consulta donde se muestra el nombre de la cancion, el nombre del autor y su duracion --
SELECT S.NOMBRE_CANCION, S.DURACION, AR.NOMBRE_ARTISTA FROM SONGS S INNER JOIN ARTIST AR ON S.ID_ARTI = AR.ID_ARTI;


-- ALBUMS --
SELECT * FROM ALBUMS;

SELECT A.NOMBRE_ALBUM, AR.NOMBRE_ARTISTA FROM ALBUMS A INNER JOIN ARTIST AR ON A.ID_ARTISTA = AR.ID_ARTI;

SELECT A.NOMBRE_ALBUM, A.FECHA_LANZAMIENTO, AR.NOMBRE_ARTISTA FROM ALBUMS A INNER JOIN ARTIST AR ON 
A.ID_ARTISTA = AR.ID_ARTI;

SELECT A.NOMBRE_ALBUM, A.DURACION FROM ALBUMS A;

SELECT DISTINCT A.NOMBRE_ALBUM, AR.NOMBRE_ARTISTA, COUNT(S.ID_ARTI) OVER (PARTITION BY S.ID_ARTI) AS NOCANCIONES
FROM ALBUMS A JOIN ARTIST AR ON A.ID_ARTISTA = AR.ID_ARTI JOIN SONGS S ON S.ID_ARTI = AR.ID_ARTI;

SELECT AR.NOMBRE_ARTISTA, A.NOMBRE_ALBUM, A.DURACION FROM ARTIST AR INNER JOIN ALBUMS A ON AR.ID_ARTI = A.ID_ARTISTA;

SELECT NOMBRE_ALBUM, FECHA_LANZAMIENTO FROM ALBUMS;

SELECT AR.NOMBRE_ARTISTA, COUNT(*) AS NOALBUMS FROM ARTIST AR INNER JOIN ALBUMS A ON AR.ID_ARTI = A.ID_ARTISTA GROUP BY AR.NOMBRE_ARTISTA;

SELECT NOMBRE_ALBUM, DURACION FROM ALBUMS;

SELECT NOMBRE_ALBUM, FECHA_LANZAMIENTO, DURACION FROM ALBUMS WHERE NOMBRE_ALBUM = 'Completely Well';

-- PLAYLIST -- 

SELECT * FROM PLAYLIST;

SELECT * FROM PLAYLIST WHERE PRIVACIDAD_PLAYLIST='PRIVADA';

SELECT COUNT(*) AS TOTAL_PLAYLIST FROM PLAYLIST;

SELECT * FROM PLAYLIST ORDER BY NOMBRE_PLAYSLIST ASC;

SELECT SUM(DURACION_PLAYSLIST)AS DURACION_TOTAL FROM PLAYLIST;

SELECT * FROM PLAYLIST WHERE PRIVACIDAD_PLAYLIST = 'PUBLICA' AND DURACION_PLAYSLIST > 4;

SELECT * FROM PLAYLIST WHERE ID_ARTI=5;

SELECT COUNT(*)AS NUMERO_PLAYLIST_PUBLICAS FROM PLAYLIST WHERE PRIVACIDAD_PLAYLIST= 'PUBLICA';

SELECT AVG(DURACION_PLAYSLIST)AS DURACION_PROMEDIO FROM PLAYLIST;

SELECT * FROM PLAYLIST WHERE DURACION_PLAYSLIST BETWEEN 3 AND 5;


-- PLAYSLIST_USUARIOS --

SELECT * FROM PLAYSLIST_USUARIOS WHERE PRIVACIDAD_PLAYLIST = 'publica';

SELECT * FROM PLAYSLIST_USUARIOS WHERE PRIVACIDAD_PLAYLIST = 'publica' AND DURACION_PLAYSLIST > 60;

SELECT * FROM PLAYSLIST_USUARIOS WHERE PRIVACIDAD_PLAYLIST = 'Privada';

SELECT * FROM PLAYSLIST_USUARIOS WHERE DURACION_PLAYSLIST <32;

SELECT * FROM PLAYSLIST_USUARIOS WHERE NOMBRE_PLAYSLIST = 'Pistiembre';

SELECT * FROM PLAYSLIST_USUARIOS WHERE NOMBRE_PLAYSLIST = 'Reggaeton';

SELECT * FROM PLAYSLIST_USUARIOS WHERE NOMBRE_PLAYSLIST = 'Viva Latino';

SELECT * FROM PLAYSLIST_USUARIOS WHERE NOMBRE_PLAYSLIST = 'Viva Latino';

SELECT * FROM PLAYSLIST_USUARIOS WHERE ID_SONGS = '19';

SELECT * FROM PLAYSLIST_USUARIOS WHERE ID_SONGS = '15';









