CREATE TABLE ARTIST(
ID_ARTI NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_ARTISTA VARCHAR2(30) NOT NULL,
NUM_SEGUIDORES NUMBER,
TOP_CANCIONES VARCHAR2(30)
);

CREATE TABLE GENEROS(
ID_GENERO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TIPO_GENERO VARCHAR2(40)
);

CREATE TABLE USUARIO(
   ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   NOMBRE_USUARIO VARCHAR2(30),
   EMAIL VARCHAR2(30),
   CONTRA VARCHAR2(15),
   SEGUIDORES NUMBER
);

CREATE TABLE SUSCRIPCION(
ID_SUSCRIPCION  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TIPO_SUB VARCHAR2(20),
ID_USUARIO NUMBER,
CONSTRAINT FK_SUSCRIPCION FOREIGN KEY(ID_USUARIO)REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE SONGS(
ID_SONGS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_CANCION VARCHAR2 (30),
DURACION NUMBER,
ID_GENERO NUMBER,
ID_ARTI NUMBER,
CONSTRAINT FK_SONGS FOREIGN KEY(ID_ARTI)REFERENCES ARTIST(ID_ARTI),
FOREIGN KEY(ID_GENERO)REFERENCES GENEROS(ID_GENERO)
);


CREATE TABLE ALBUMS(
ID_ALBUMS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_ALBUM VARCHAR2(60),
FECHA_LANZAMIENTO DATE,
DURACION NUMBER,
ID_ARTISTA NUMBER,
ID_SONGS NUMBER,

CONSTRAINT FK_ALBUMS FOREIGN KEY (ID_ARTISTA) REFERENCES ARTIST(ID_ARTI),
FOREIGN KEY (ID_SONGS) REFERENCES SONGS(ID_SONGS)
);

CREATE TABLE PLAYLIST(
ID_PLAYLIST NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_PLAYSLIST VARCHAR2(40),
PRIVACIDAD_PLAYLIST VARCHAR2(30),
DURACION_PLAYSLIST NUMBER,
ID_SONGS NUMBER,

CONSTRAINT FK_PLAYSLIST FOREIGN KEY(ID_SONGS)REFERENCES SONGS(ID_SONGS)
);

CREATE TABLE PLAYSLIST_USUARIOS(
ID_PLAYLIST_USUARIOS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_PLAYSLIST VARCHAR2(40),
PRIVACIDAD_PLAYLIST VARCHAR2(30),
DURACION_PLAYSLIST NUMBER,
ID_SONGS NUMBER,
ID_USUA NUMBER,

CONSTRAINT FK_PLAYSLIST_USUARIOS FOREIGN KEY(ID_SONGS)REFERENCES SONGS(ID_SONGS),
FOREIGN KEY(ID_USUA)REFERENCES USUARIO(ID_USUARIO)
);


